  name: GitHub Organization User Activity Report
  on: [push]
  jobs: 
    analyze:
      name: analyze org
      runs-on: ubuntu-latest
      steps:
        - name: Org User Activity
          id: github_user_analysis
          uses: peter-murray/inactive-users-action@v1
          with:
            token: ${{ secrets.USER_ACCESS_HISTORY }}
            organization: Instrument
            activity_days: 90
        - name: Save User Activity Report
          uses: actions/upload-artifact@v2
          with:
            name: user_report
            path: ${{ steps.github_user_analysis.outputs.report_csv }}
